linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - elseif

linters:
  enable:
    - gofmt
    - gocritic
    - unconvert
    - govet
    - revive
issues:
  exclude-dirs:
    - kschat/types/
